# Build settings
plugins:
  - jemoji
  - jekyll-paginate
permalink: /:categories/:title/

# Site settings
title: "Salvatore's Blog"
description: >
   It works on my computer.

email: sal.testa@gmail.com
#blog logo
logo: "/assets/images/sal_logo.jpg"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/open_office_1920_1440.jpg"

name: 'Salvatore Testa'
author: 'Salvatore Testa'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "https://saltesta.com" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@saltesta14'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

# social icons and sharing options
social:
  - icon: envelope
    url:  mailto:sal.testa@gmail.com
    desc: Shoot me an email
    share_url:
    share_title:
    share_link:

  - icon: twitter
    url:  https://twitter.com/saltesta14
    desc: Follow me on Twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	facebook
    url:	https://facebook.com/stesta
    desc: Connect with me Facebook
    share_url:
    share_title:
    share_link:

  - icon:	github
    url:	https://github.com/salvatoret
    desc:	Fork me on GitHub
    share_url:
    share_title:
    share_link:

  - icon: linkedin-square
    url:  https://www.linkedin.com/in/saltesta
    desc: Add me on LinkedIn
    share_url:
    share_title:
    share_link:

  - icon: instagram
    url:  https://www.instagram.com/saltesta/
    desc: See what I'm up to on Instagram
    share_url:
    share_title:
    share_link:
